### PR TITLE
Indicate local time and Singapore time on view event page

### PR DESCRIPTION
**Pull request by KangJingA**

### CODE REVIEW

**Comment by chrisjensen** [comment]
Hi Nick, I thought you also discovered there was a page that was using `{{prettyDate}}` which would format the date in the local time. Can we update that page to use the SG time
Might also be worth getting the input component to assume SG time (and describe it accordingly) so that people like Eden who are living overseas don't get confused when entering a time into the form.

**Review by chrisjensen — CHANGES_REQUESTED** [review]
As above

**Comment by chrisjensen** [comment]
Hi Nick this looks good, but can you please confirm if you've checked that the form inputs also work properly when creating/editing an event from outside singapore

**Comment by chrisjensen** [comment]
Hi Nick, still looking for a response on ☝️

**Comment by KangJingA** [comment]
Hey Chris, 

So sorry for the late reply, the form inputs work fine!

**Review by chrisjensen — APPROVED** [review]

**Pull request merged**
